#!/usr/bin/env python3
"""Generate the per-tool argument declarations from the conformance golden.

Milestone C needs, for every tool it can run, the flattened argument namespace the reference's
own parser produces: 70 named arguments for a read walker, of which the tool itself writes a
handful. Hand-writing that is neither cheap nor checkable, and reading it off the tool's usage
text gives a different, shorter list (the usage prints 42 of the 70).

So the declarations are generated from the `tool-argument-declarations` golden, which is the
reference's own `getNamedArgumentDefinitions()` on the parser the tool hands out. The generated
module is data, and the test beside it checks that data against a second, independent reading:
the inventory, which comes from the reference's CLI rather than from its reflection.
"""

import argparse
import gzip
import json
import pathlib
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parents[2]
GOLDEN = REPO / "crates/gatk-tools/tests/data/tool_declarations.txt.gz"
ENUMS = REPO / "crates/gatk-tools/tests/data/tool_argument_enums.txt.gz"
OUT = REPO / "crates/gatk-tools/src/tool_declarations.rs"
INVENTORY = REPO / "tools/inventory/generated/inventory.json"

HEADER = '''//! The argument declarations of the tools Milestone C can run, as the reference's own parser
//! reports them.
//!
//! Generated by `tools/declarations/generate.py` from the `tool-argument-declarations` golden. Do
//! not edit by hand.
//!
//! The list is the parser the TOOL hands out, not one built from an instance: the second knows
//! nothing about the plugin descriptors or the standard collections, and is short by half.

/// One named argument, as the parser reports it.
///
/// `Eq` is deliberately absent: the two ranges are doubles, and an undeclared one is an infinity
/// rather than a missing value, so equality here is the doubles' own.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Declaration {
    /// The `--long-name`, without its dashes.
    pub long_name: &'static str,
    /// Every alias the parser answers to, long and short, in its own order.
    pub aliases: &'static [&'static str],
    /// Whether the parser refuses a command line that leaves it out.
    pub required: bool,
    /// Whether naming it twice is two values rather than an error.
    pub collection: bool,
    /// The value a constructed instance holds, as the parser renders it.
    pub default: Option<&'static str>,
    /// The UNDERLYING field's class, which for a collection is its element class: `--input` is a
    /// `List<GATKPath>` and reports `GATKPath`, so the conversion is the element's.
    pub type_name: &'static str,
    /// Whether the field is a primitive, which is a separate question from the class: the class
    /// is boxed either way, and only the null check asks this one.
    pub primitive: bool,
    /// Whether the argument takes no value.
    pub flag: bool,
    /// Whether the usage text leaves it out altogether.
    pub hidden: bool,
    /// Whether it belongs under the usage's advanced section.
    pub advanced: bool,
    /// Whether it is one of the arguments every tool inherits rather than one of its own.
    pub common: bool,
    /// How many values a collection accepts, which is `0` and `i32::MAX` unless declared.
    pub min_elements: i32,
    pub max_elements: i32,
    /// The hard range, as doubles, infinite when undeclared.
    pub min_value: f64,
    pub max_value: f64,
    /// The recommended range, which is declared BESIDE the hard one and not instead of it.
    pub min_recommended_value: f64,
    pub max_recommended_value: f64,
    /// The arguments this one may not be given with.
    pub mutex: &'static [&'static str],
    /// The plugin descriptor that controls this argument, if it is not the tool's own.
    pub controlled_by: Option<&'static str>,
    /// The `@Argument` annotation's documentation string, which is what the usage text wraps.
    pub doc: &'static str,
}

/// One enum type an argument's value is converted with.
///
/// The constants are in DECLARATION order, which is what `values()` returns and what the message a
/// bad value produces lists. `docs` is empty unless the enum implements Barclay's `ClpEnum`, in
/// which case it is the documentation the usage text prints beside each constant.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EnumType {
    pub name: &'static str,
    pub constants: &'static [&'static str],
    pub docs: &'static [(&'static str, &'static str)],
}

'''


def literal(text):
    """A Rust string literal for a golden's own escaping, unescaped back to its bytes."""
    body = text.replace("\\t", "\t").replace("\\n", "\n")
    escaped = (body.replace("\\", "\\\\").replace('"', '\\"')
               .replace("\t", "\\t").replace("\n", "\\n"))
    return f'"{escaped}"'


def rust_double(text):
    """`String.valueOf(Double)` renders the infinities as words, and Rust names them differently."""
    return {
        "Infinity": "f64::INFINITY",
        "-Infinity": "f64::NEG_INFINITY",
        "null": "f64::NAN",
    }.get(text, text)


def rows(text, kind, tool):
    prefix = f"{kind}\t{tool}\t"
    return [line[len(prefix):] for line in text.split("\n") if line.startswith(prefix)]


def rustfmt(text):
    """Run the generated module through rustfmt, so `cargo fmt` and this generator agree.

    Without it the two fight: the generator writes one alias list per line and rustfmt wraps the
    long ones, so a formatted tree fails `--check` and a regenerated tree fails `cargo fmt`.
    """
    with tempfile.NamedTemporaryFile("w", suffix=".rs", delete=False) as handle:
        handle.write(text)
        path = handle.name
    subprocess.run(["rustfmt", "--edition", "2021", path], check=True)
    formatted = pathlib.Path(path).read_text()
    pathlib.Path(path).unlink()
    return formatted


def cross_check(tool, entries):
    """Check the generated list against the inventory, which reads the reference's CLI.

    The two are different readings of the same reference: the golden is `getNamedArgumentDefinitions`
    on the parser the tool hands out, the inventory is the usage text the same tool prints. Every
    documented argument has to be in the declarations, with the same `required` and the same
    default. The declarations hold more, because the usage text does not print the common and
    advanced ones.
    """
    inventory = json.loads(INVENTORY.read_text())
    documented = next(t for t in inventory["tools"] if t["name"] == tool)["arguments"]
    by_name = {entry["long_name"]: entry for entry in entries}
    for argument in documented:
        name = argument["name"].lstrip("-")
        entry = by_name.get(name)
        if entry is None:
            sys.exit(f"{tool}: the usage text documents --{name} and the parser does not declare it")
        if entry["required"] != bool(argument["required"]):
            sys.exit(f"{tool}: --{name} is required in one reading and not the other")
        written = argument.get("default")
        if written is None:
            continue
        ours = entry["default"]
        # The two readings render two things differently and agree on everything else: an empty
        # collection is `null` from the definition and `[]` in the usage text, and an empty string
        # scalar is the empty string in one and `""` in the other. Both are the same fact twice.
        if ours == written:
            continue
        if ours is None and written == "[]":
            continue
        if ours == "" and written == '""':
            continue
        sys.exit(
            f"{tool}: --{name} defaults to {ours!r} in the parser and {written!r} in the usage text"
        )
    # The usage text never prints MORE than the parser declares. It prints fewer for a walker,
    # whose plugin descriptors and standard collections it leaves out, and exactly as many for a
    # tool that has neither: IndexFeatureFile is 14 of 14.
    if len(documented) > len(entries):
        sys.exit(f"{tool}: the usage text prints {len(documented)} of {len(entries)} declarations")
    return len(documented)


def summary_table(tools):
    """The one-line summary the usage header prints, taken from the inventory.

    It is the only piece of a tool's usage that is not in the declarations golden: the header's
    second paragraph is the tool's own `oneLineSummary`, which the inventory carries because it
    reads the reference's machine-readable documentation.
    """
    inventory = json.loads(INVENTORY.read_text())
    by_name = {tool["name"]: tool for tool in inventory["tools"]}
    arms = []
    for tool in tools:
        summary = by_name[tool]["summary"]
        arms.append(f'        "{tool}" => Some({literal(summary)}),')
    return (
        "/// The one-line summary the usage header prints, from the inventory.\n"
        "pub fn summary(tool: &str) -> Option<&'static str> {\n"
        "    match tool {\n" + "\n".join(arms) + "\n        _ => None,\n    }\n}\n"
    )


def enum_table():
    """The enum types, from the `tool-argument-enums` golden.

    A declaration says an argument's type is `IntervalSetRule`. Converting a value needs to know
    what one is, and the message a bad value produces lists every constant, so the table is by
    type rather than by tool: the same type is named by several tools and is one type.
    """
    if not ENUMS.exists():
        sys.exit(f"no golden at {ENUMS}")
    text = gzip.open(ENUMS, "rt").read()
    docs = {}
    for line in text.split("\n"):
        if line.startswith("clp\t"):
            _, name, body = line.split("\t", 2)
            constant, doc = body.split("=", 1)
            docs.setdefault(name, []).append((constant, doc))
    entries = []
    for line in text.split("\n"):
        if not line.startswith("enum\t"):
            continue
        _, name, constants = line.split("\t", 2)
        listed = ", ".join(f'"{constant}"' for constant in constants.split(","))
        written = ", ".join(
            f"({literal(constant)}, {literal(doc)})" for constant, doc in docs.get(name, []))
        entries.append(
            "    EnumType {\n"
            f'        name: "{name}",\n'
            f"        constants: &[{listed}],\n"
            f"        docs: &[{written}],\n"
            "    },")
    return (
        "/// The enum types the ported tools name, by type and not by tool.\n"
        "pub const ENUM_TYPES: &[EnumType] = &[\n" + "\n".join(entries) + "\n];\n\n"
        "/// The type a declaration's `type_name` names, if it is an enum.\n"
        "pub fn enum_type(name: &str) -> Option<&'static EnumType> {\n"
        "    ENUM_TYPES.iter().find(|type_| type_.name == name)\n}\n"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if the generated module is not what this would write")
    options = parser.parse_args()
    if not GOLDEN.exists():
        sys.exit(f"no golden at {GOLDEN}")
    text = gzip.open(GOLDEN, "rt").read()
    tools = []
    for line in text.split("\n"):
        if line.startswith("count\t"):
            tools.append(line.split("\t")[1])
    out = [HEADER]
    for tool in tools:
        constant = tool.upper()
        parsed = []
        entries = []
        docs = {}
        for row in rows(text, "doc", tool):
            index, body = row.split("\t", 1)
            docs[index] = body
        for row in rows(text, "def", tool):
            index, body = row.split("\t", 1)
            fields = body.split("|")
            if len(fields) != 19:
                sys.exit(f"{tool}: a def line has {len(fields)} fields and not 19")
            (long_name, aliases, required, collection, default, type_name, primitive, flag,
             hidden, advanced, common, min_elements, max_elements, min_value, max_value,
             min_recommended, max_recommended, mutex, plugin) = fields
            alias_list = ", ".join(f'"{a}"' for a in aliases.split(",") if a)
            default_literal = (
                "None" if default == "null" else 'Some(%s)' % literal(default)
            )
            mutex_list = "" if mutex == "none" else ", ".join(
                f'"{name}"' for name in mutex.split(","))
            parsed.append({
                "long_name": long_name,
                "required": required == "required",
                "default": None if default == "null" else default,
            })
            entries.append(
                "    Declaration {\n"
                f'        long_name: "{long_name}",\n'
                f"        aliases: &[{alias_list}],\n"
                f"        required: {'true' if required == 'required' else 'false'},\n"
                f"        collection: {'true' if collection == 'collection' else 'false'},\n"
                f"        default: {default_literal},\n"
                f'        type_name: "{type_name}",\n'
                f"        primitive: {'true' if primitive == 'primitive' else 'false'},\n"
                f"        flag: {'true' if flag == 'flag' else 'false'},\n"
                f"        hidden: {'true' if hidden == 'hidden' else 'false'},\n"
                f"        advanced: {'true' if advanced == 'advanced' else 'false'},\n"
                f"        common: {'true' if common == 'common' else 'false'},\n"
                f"        min_elements: {min_elements},\n"
                f"        max_elements: {max_elements},\n"
                f"        min_value: {rust_double(min_value)},\n"
                f"        max_value: {rust_double(max_value)},\n"
                f"        min_recommended_value: {rust_double(min_recommended)},\n"
                f"        max_recommended_value: {rust_double(max_recommended)},\n"
                f"        mutex: &[{mutex_list}],\n"
                f"        controlled_by: {'None' if plugin == 'none' else 'Some(\"%s\")' % plugin},\n"
                f"        doc: {literal(docs.get(index, ''))},\n"
                "    },"
            )
        documented = cross_check(tool, parsed)
        out.append(
            f"/// `{tool}`'s namespace, in the parser's own order.\n"
            f"///\n"
            f"/// {len(entries)} named arguments, of which the usage text prints {documented}.\n"
            f"pub const {constant}: &[Declaration] = &[\n" + "\n".join(entries) + "\n];\n"
        )
    out.append(summary_table(tools))
    out.append(enum_table())
    arms = "\n".join(f'        "{tool}" => Some({tool.upper()}),' for tool in tools)
    out.append(
        "/// The declarations of one tool, by the name `gatk <Tool>` resolves.\n"
        "pub fn declarations(tool: &str) -> Option<&'static [Declaration]> {\n"
        "    match tool {\n" + arms + "\n        _ => None,\n    }\n}\n"
    )
    text = rustfmt("\n".join(out))
    if options.check:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit(f"{OUT.relative_to(REPO)} is not what generate.py writes; re-run it")
        print(f"{OUT.relative_to(REPO)} is up to date: {len(tools)} tools")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO)}: {len(tools)} tools")


if __name__ == "__main__":
    main()
