#!/usr/bin/env python3
"""Generate the per-tool argument declarations from the conformance golden.

Milestone C needs, for every tool it can run, the flattened argument namespace the reference's
own parser produces: 70 named arguments for a read walker, of which the tool itself writes a
handful. Hand-writing that is neither cheap nor checkable, and reading it off the tool's usage
text gives a different, shorter list (the usage prints 42 of the 70).

So the declarations are generated from the `tool-argument-declarations` golden, which is the
reference's own `getNamedArgumentDefinitions()` on the parser the tool hands out. The generated
module is data, and the test beside it checks that data against a second, independent reading:
the inventory, which comes from the reference's CLI rather than from its reflection.
"""

import argparse
import gzip
import json
import pathlib
import subprocess
import sys
import tempfile

REPO = pathlib.Path(__file__).resolve().parents[2]
GOLDEN = REPO / "crates/gatk-tools/tests/data/tool_declarations.txt.gz"
OUT = REPO / "crates/gatk-tools/src/tool_declarations.rs"
INVENTORY = REPO / "tools/inventory/generated/inventory.json"

HEADER = '''//! The argument declarations of the tools Milestone C can run, as the reference's own parser
//! reports them.
//!
//! Generated by `tools/declarations/generate.py` from the `tool-argument-declarations` golden. Do
//! not edit by hand.
//!
//! The list is the parser the TOOL hands out, not one built from an instance: the second knows
//! nothing about the plugin descriptors or the standard collections, and is short by half.

/// One named argument, as the parser reports it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Declaration {
    /// The `--long-name`, without its dashes.
    pub long_name: &'static str,
    /// Every alias the parser answers to, long and short, in its own order.
    pub aliases: &'static [&'static str],
    /// Whether the parser refuses a command line that leaves it out.
    pub required: bool,
    /// Whether naming it twice is two values rather than an error.
    pub collection: bool,
    /// The value a constructed instance holds, as the parser renders it.
    pub default: Option<&'static str>,
}

'''


def rows(text, kind, tool):
    prefix = f"{kind}\t{tool}\t"
    return [line[len(prefix):] for line in text.split("\n") if line.startswith(prefix)]


def rustfmt(text):
    """Run the generated module through rustfmt, so `cargo fmt` and this generator agree.

    Without it the two fight: the generator writes one alias list per line and rustfmt wraps the
    long ones, so a formatted tree fails `--check` and a regenerated tree fails `cargo fmt`.
    """
    with tempfile.NamedTemporaryFile("w", suffix=".rs", delete=False) as handle:
        handle.write(text)
        path = handle.name
    subprocess.run(["rustfmt", "--edition", "2021", path], check=True)
    formatted = pathlib.Path(path).read_text()
    pathlib.Path(path).unlink()
    return formatted


def cross_check(tool, entries):
    """Check the generated list against the inventory, which reads the reference's CLI.

    The two are different readings of the same reference: the golden is `getNamedArgumentDefinitions`
    on the parser the tool hands out, the inventory is the usage text the same tool prints. Every
    documented argument has to be in the declarations, with the same `required` and the same
    default. The declarations hold more, because the usage text does not print the common and
    advanced ones.
    """
    inventory = json.loads(INVENTORY.read_text())
    documented = next(t for t in inventory["tools"] if t["name"] == tool)["arguments"]
    by_name = {entry["long_name"]: entry for entry in entries}
    for argument in documented:
        name = argument["name"].lstrip("-")
        entry = by_name.get(name)
        if entry is None:
            sys.exit(f"{tool}: the usage text documents --{name} and the parser does not declare it")
        if entry["required"] != bool(argument["required"]):
            sys.exit(f"{tool}: --{name} is required in one reading and not the other")
        written = argument.get("default")
        if written is None:
            continue
        ours = entry["default"]
        # The two readings render two things differently and agree on everything else: an empty
        # collection is `null` from the definition and `[]` in the usage text, and an empty string
        # scalar is the empty string in one and `""` in the other. Both are the same fact twice.
        if ours == written:
            continue
        if ours is None and written == "[]":
            continue
        if ours == "" and written == '""':
            continue
        sys.exit(
            f"{tool}: --{name} defaults to {ours!r} in the parser and {written!r} in the usage text"
        )
    # The usage text never prints MORE than the parser declares. It prints fewer for a walker,
    # whose plugin descriptors and standard collections it leaves out, and exactly as many for a
    # tool that has neither: IndexFeatureFile is 14 of 14.
    if len(documented) > len(entries):
        sys.exit(f"{tool}: the usage text prints {len(documented)} of {len(entries)} declarations")
    return len(documented)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if the generated module is not what this would write")
    options = parser.parse_args()
    if not GOLDEN.exists():
        sys.exit(f"no golden at {GOLDEN}")
    text = gzip.open(GOLDEN, "rt").read()
    tools = []
    for line in text.split("\n"):
        if line.startswith("count\t"):
            tools.append(line.split("\t")[1])
    out = [HEADER]
    for tool in tools:
        constant = tool.upper()
        parsed = []
        entries = []
        for row in rows(text, "def", tool):
            _, body = row.split("\t", 1)
            long_name, aliases, required, collection, default = body.split("|", 4)
            alias_list = ", ".join(f'"{a}"' for a in aliases.split(",") if a)
            default_literal = (
                "None" if default == "null" else 'Some("%s")' % default.replace('"', '\\"')
            )
            parsed.append({
                "long_name": long_name,
                "required": required == "required",
                "default": None if default == "null" else default,
            })
            entries.append(
                "    Declaration {\n"
                f'        long_name: "{long_name}",\n'
                f"        aliases: &[{alias_list}],\n"
                f"        required: {'true' if required == 'required' else 'false'},\n"
                f"        collection: {'true' if collection == 'collection' else 'false'},\n"
                f"        default: {default_literal},\n"
                "    },"
            )
        documented = cross_check(tool, parsed)
        out.append(
            f"/// `{tool}`'s namespace, in the parser's own order.\n"
            f"///\n"
            f"/// {len(entries)} named arguments, of which the usage text prints {documented}.\n"
            f"pub const {constant}: &[Declaration] = &[\n" + "\n".join(entries) + "\n];\n"
        )
    arms = "\n".join(f'        "{tool}" => Some({tool.upper()}),' for tool in tools)
    out.append(
        "/// The declarations of one tool, by the name `gatk <Tool>` resolves.\n"
        "pub fn declarations(tool: &str) -> Option<&'static [Declaration]> {\n"
        "    match tool {\n" + arms + "\n        _ => None,\n    }\n}\n"
    )
    text = rustfmt("\n".join(out))
    if options.check:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit(f"{OUT.relative_to(REPO)} is not what generate.py writes; re-run it")
        print(f"{OUT.relative_to(REPO)} is up to date: {len(tools)} tools")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO)}: {len(tools)} tools")


if __name__ == "__main__":
    main()
