#!/usr/bin/env python3
"""Generate the main usage listing's catalogue from the conformance golden.

The listing `gatk` prints with no arguments is 373 lines, and 353 of them are a tool's display
name and its one-line summary. That data is the reference's annotations, not this port's opinion,
so it is generated from the `main-usage` golden rather than written: `@CommandLineProgramProperties`
gives the group and the summary, `@BetaFeature` and `@ExperimentalFeature` give the marker, and
`RuntimeUtils.toolDisplayName` gives the ` (Picard)` suffix.

What is NOT generated is the layout, which is `Main.printUsage` and is ported in
`crates/gatk-tools/src/main_usage.rs`. That is the division this file exists to keep: the data is
the reference's and is copied, the rendering is the port's and is compared.

    python3 tools/declarations/generate_usage.py           # write the module
    python3 tools/declarations/generate_usage.py --check   # fail if it is stale
"""

import argparse
import gzip
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
GOLDEN = REPO / "crates/gatk-tools/tests/data/main_usage.txt.gz"
OUT = REPO / "crates/gatk-tools/src/main_usage_catalogue.rs"

HEADER = '''//! Every tool the main usage listing names, and every group it sorts them into.
//!
//! Generated by `tools/declarations/generate_usage.py` from the `main-usage` golden. Do not edit
//! by hand.
//!
//! This is the reference's own annotations and nothing else: `@CommandLineProgramProperties` for
//! the group and the one-line summary, `@BetaFeature` and `@ExperimentalFeature` for the marker,
//! and `RuntimeUtils.toolDisplayName` for the ` (Picard)` suffix a Picard tool's name carries.
//!
//! The LAYOUT is not here. It is [`crate::main_usage`], which is a port of `Main.printUsage` and
//! is compared against the golden's rendered lines: the data is copied, the rendering is measured.

/// Whether Barclay marks a tool, which is a phrase inside its line rather than a property of it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Maturity {
    Released,
    Beta,
    Experimental,
}

/// One tool of the listing.
#[derive(Debug, Clone, Copy)]
pub struct Tool {
    /// `toolDisplayName`: the simple name, plus ` (Picard)` where the class is Picard's.
    pub display_name: &'static str,
    /// The SIMPLE name, which is what decides the padding: a Picard tool whose simple name is
    /// under 45 characters is padded even when its display name is over.
    pub simple_name: &'static str,
    /// The program group's class name, which is the key the groups are keyed by.
    pub group: &'static str,
    pub maturity: Maturity,
    pub one_line_summary: &'static str,
}

/// One program group: the heading, and the line under it.
#[derive(Debug, Clone, Copy)]
pub struct Group {
    pub class: &'static str,
    pub name: &'static str,
    pub description: &'static str,
}

'''


def read_golden(path):
    with gzip.open(path, "rt") as handle:
        return handle.read()


def unescape(text):
    return text.replace("\\t", "\t").replace("\\n", "\n").replace("\\\\", "\\")


def rust_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(dump):
    groups = []
    tools = []
    for line in dump.splitlines():
        parts = line.split("\t")
        if parts[0] == "group":
            groups.append((parts[1], unescape(parts[2]), unescape(parts[3])))
        elif parts[0] == "tool":
            # display name, group class, maturity, simple name, one-line summary
            tools.append((parts[1], parts[2], parts[3], parts[4], unescape(parts[5])))

    out = [HEADER]
    out.append(f"/// The {len(groups)} groups, sorted by class name as the golden carries them.\n")
    out.append("pub const GROUPS: &[Group] = &[\n")
    for cls, name, description in groups:
        out.append("    Group {\n")
        out.append(f"        class: {rust_string(cls)},\n")
        out.append(f"        name: {rust_string(name)},\n")
        out.append(f"        description: {rust_string(description)},\n")
        out.append("    },\n")
    out.append("];\n\n")

    out.append(f"/// The {len(tools)} tools, sorted by display name as the golden carries them.\n")
    out.append("pub const TOOLS: &[Tool] = &[\n")
    for display, group, maturity, simple, summary in tools:
        kind = {"released": "Released", "beta": "Beta", "experimental": "Experimental"}[maturity]
        out.append("    Tool {\n")
        out.append(f"        display_name: {rust_string(display)},\n")
        out.append(f"        simple_name: {rust_string(simple)},\n")
        out.append(f"        group: {rust_string(group)},\n")
        out.append(f"        maturity: Maturity::{kind},\n")
        out.append(f"        one_line_summary: {rust_string(summary)},\n")
        out.append("    },\n")
    out.append("];\n")
    return "".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--dump", help="read this dump instead of the committed golden")
    args = parser.parse_args()

    if args.dump:
        dump = pathlib.Path(args.dump).read_text()
    elif GOLDEN.exists():
        dump = read_golden(GOLDEN)
    elif args.check:
        # The suite is still `golden-pending` (decision 0008): the module was generated from the
        # run that produced the candidate, and there is nothing yet to re-derive it from. Saying so
        # is the honest gate; failing would make the two-commit flow impossible to walk.
        print(f"skipped: no golden at {GOLDEN} yet, so {OUT.name} cannot be re-derived")
        return 0
    else:
        print(f"no golden at {GOLDEN} and no --dump given", file=sys.stderr)
        return 1

    rendered = render(dump)
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != rendered:
            print(f"{OUT} is stale: regenerate with tools/declarations/generate_usage.py")
            return 1
        tools = rendered.count("    Tool {\n")
        print(f"{OUT.relative_to(REPO)} is up to date: {tools} tools")
        return 0

    OUT.write_text(rendered)
    print(f"wrote {OUT} ({rendered.count('    Tool {')} tools, {rendered.count('    Group {')} groups)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
