//! `AS_QualByDepth`, `AS_RMSMappingQuality` and `AS_InbreedingCoeff`, ported from GATK 4.6.2.0.
//!
//! The last three allele-specific annotations, and the three that share least: one has no raw form
//! at all, one keeps a sum of squares per allele, and one is not reducible and does not inherit from
//! its non-allele-specific sibling.
//!
//! # `AS_QD` has no raw data of its own and refuses to say so
//!
//! ```java
//! public Map<String, Object> annotateRawData(...) { return Collections.emptyMap(); }
//! ```
//!
//! "We expect the `AS_QUAL` key to be generated by GenotypeGVCFs during genotyping." So the raw key
//! `AS_QUALapprox` is declared, its combine step exists, and the annotation that would produce it
//! does not. `annotate` is `finalizeRawData(vc, vc)` with the same context passed twice.
//!
//! # `AS_QD` inherits the randomised branch, once per alternate allele
//!
//! ```java
//! AS_QD = QualByDepth.fixTooHighQD(AS_QD);
//! ```
//!
//! Each alternate's quality-by-depth goes through the same replacement at 35 that `QD` does, so a
//! multiallelic site can have one deterministic entry and one drawn from a random generator in the
//! same comma-separated field. This port refuses each entry that reaches the branch, for the reason
//! recorded in [`crate::site_statistics`], and reports which ones.
//!
//! # The reference depth is added to **every** alternate's denominator
//!
//! ```java
//! double AS_QD = alleleQualList.get(i) / ((double)standardDepth.get(i+1) + refDepth);
//! ```
//!
//! "add ref counts to each to match biallelic case". So the denominators of a triallelic site
//! overlap: the reference reads are counted once for each alternate, and the entries do not sum to
//! anything meaningful.
//!
//! # `AS_MQ` divides a sum of squares by an `AD` the annotation did not compute
//!
//! ```java
//! Math.sqrt((double) perAlleleValues.get(current) / variantADs.get(current))
//! ```
//!
//! The numerator comes from the likelihood matrix (or from a parsed raw string) and the denominator
//! from the genotypes' `AD` fields, summed over samples. Nothing checks that the two describe the
//! same reads. An allele with a sum of squares and an `AD` of zero divides by zero and the entry is
//! `Infinity`; an allele present in the map with a null value is the missing value instead.
//!
//! # `AS_InbreedingCoeff` is the only one that is not reducible
//!
//! It implements `InfoFieldAnnotation` directly rather than extending `InbreedingCoeff`, with a
//! comment saying that inheriting would force it to be output all the time. The duplication is
//! visible: it has its own ten-sample minimum, counted on
//! [`crate::heterozygosity::heterozygosity_counts`] rather than on the genotype counts, and its
//! biallelic branch derives the allele frequency from the allele counts while its multiallelic
//! branch derives it from `getCalledChrCount`. The two do not agree.

use gatk_engine::allele_likelihoods::AlleleLikelihoods;
use gatk_engine::read::mapping_quality;
use htsjdk_bam::record::BamRecord;
use htsjdk_vcf::allele::Allele;
use htsjdk_vcf::variant::VariantContext;

use crate::heterozygosity::{heterozygosity_counts, HeterozygosityCounts};
use crate::rank_sum::format_decimals;
use crate::site_statistics::QualByDepthError;

/// `GATKVCFConstants.AS_QUAL_BY_DEPTH_KEY`.
pub const AS_QUAL_BY_DEPTH_KEY: &str = "AS_QD";
/// `GATKVCFConstants.AS_QUAL_KEY`.
pub const AS_QUAL_KEY: &str = "AS_QUAL";
/// `GATKVCFConstants.AS_RAW_QUAL_APPROX_KEY`.
pub const AS_RAW_QUAL_APPROX_KEY: &str = "AS_QUALapprox";
/// `GATKVCFConstants.AS_VARIANT_DEPTH_KEY`.
pub const AS_VARIANT_DEPTH_KEY: &str = "AS_VarDP";
/// `GATKVCFConstants.AS_RMS_MAPPING_QUALITY_KEY`.
pub const AS_RMS_MAPPING_QUALITY_KEY: &str = "AS_MQ";
/// `GATKVCFConstants.AS_RAW_RMS_MAPPING_QUALITY_KEY`.
pub const AS_RAW_RMS_MAPPING_QUALITY_KEY: &str = "AS_RAW_MQ";
/// `GATKVCFConstants.AS_INBREEDING_COEFFICIENT_KEY`.
pub const AS_INBREEDING_COEFFICIENT_KEY: &str = "AS_InbreedingCoeff";

/// `AnnotationUtils.ALLELE_SPECIFIC_RAW_DELIM`.
const RAW_DELIM: char = '|';
/// `AnnotationUtils.LIST_DELIMITER`.
const LIST_DELIMITER: char = ',';
/// `VCFConstants.MISSING_VALUE_v4` and `AnnotationUtils.MISSING_VALUE`, which are the same dot.
const MISSING_VALUE: &str = ".";
/// `AS_InbreedingCoeff.MIN_SAMPLES`.
const MIN_SAMPLES: usize = 10;
/// `QualByDepth.MAX_QD_BEFORE_FIXING`.
const MAX_QD_BEFORE_FIXING: f64 = 35.0;

/// What this family refuses.
#[derive(Debug, Clone, PartialEq)]
pub enum AsSiteStatisticError {
    /// `IllegalStateException`: "Number of AS_QUAL values doesn't match the number of alternate
    /// alleles."
    QualCountMismatch { found: usize, expected: usize },
    /// `IllegalStateException`: "Number of AS_QUALapprox values doesn't match the number of alleles
    /// in the variant context."
    QualApproxCountMismatch { found: usize, expected: usize },
    /// `NumberFormatException`.
    Malformed { raw: String },
}

/// `AS_QualByDepth.parseQualList`: the per-alternate qualities, from either key.
///
/// `AS_QUAL` carries one value per **alternate**; `AS_QUALapprox` carries one per **allele** and its
/// first slot, the reference's, is dropped. An empty slot in the second form reads as zero, which
/// the first form has no way to express.
pub fn parse_qual_list(
    num_alleles: usize,
    as_qual: Option<&str>,
    as_raw_qual_approx: Option<&str>,
) -> Result<Vec<i32>, AsSiteStatisticError> {
    if let Some(text) = as_qual {
        let values: Vec<&str> = text.split(LIST_DELIMITER).collect();
        if values.len() != num_alleles - 1 {
            return Err(AsSiteStatisticError::QualCountMismatch {
                found: values.len(),
                expected: num_alleles - 1,
            });
        }
        return values
            .iter()
            .map(|value| {
                value
                    .trim()
                    .parse::<i32>()
                    .map_err(|_| AsSiteStatisticError::Malformed {
                        raw: value.to_string(),
                    })
            })
            .collect();
    }
    if let Some(text) = as_raw_qual_approx {
        // `replaceAll("\\[\\]\\s", "")` is a character class, so it strips brackets **and**
        // whitespace anywhere, not a bracketed prefix.
        let cleaned: String = text
            .chars()
            .filter(|c| *c != '[' && *c != ']' && !c.is_whitespace())
            .collect();
        // `split(regex, -1)`, which keeps trailing empty tokens.
        let values: Vec<&str> = cleaned.split(RAW_DELIM).collect();
        if values.len() != num_alleles {
            return Err(AsSiteStatisticError::QualApproxCountMismatch {
                found: values.len(),
                expected: num_alleles,
            });
        }
        let mut out = Vec::new();
        for value in values.iter().skip(1) {
            if value.is_empty() {
                out.push(0);
            } else {
                out.push(
                    value
                        .parse::<i32>()
                        .map_err(|_| AsSiteStatisticError::Malformed {
                            raw: value.to_string(),
                        })?,
                );
            }
        }
        return Ok(out);
    }
    Ok(Vec::new())
}

/// `AS_QualByDepth.getAlleleDepths`: the `AD`s summed over the variant genotypes.
///
/// `None` is the reference's null, meaning no genotype had an `AD` at all. A sample whose alternate
/// depth is one or less contributes **nothing**, not even its reference reads, which is the same
/// rule `QualByDepth.getDepth` applies to its AD-restricted tally.
pub fn allele_depths(vc: &VariantContext) -> Option<Vec<i32>> {
    let num_alleles = vc
        .genotypes
        .iter()
        .find_map(|genotype| genotype.ad.as_ref().map(|ad| ad.len()))?;
    let mut depths = vec![0i32; num_alleles];
    for genotype in &vc.genotypes {
        // "we care only about genotypes with variant alleles": het or hom-var.
        if !is_het_or_hom_var(genotype) {
            continue;
        }
        let Some(ad) = &genotype.ad else { continue };
        let total: i32 = ad.iter().sum();
        if total - ad[0] > 1 {
            for (index, value) in ad.iter().enumerate() {
                if index < depths.len() {
                    depths[index] += value;
                }
            }
        }
    }
    Some(depths)
}

/// `Genotype.isHet() || isHomVar()`, which is the same test `QualByDepth` uses.
fn is_het_or_hom_var(genotype: &htsjdk_vcf::variant::Genotype) -> bool {
    let called: Vec<&Allele> = genotype
        .alleles
        .iter()
        .filter(|a| !a.is_no_call())
        .collect();
    called.len() >= 2 && !called.iter().all(|a| a.is_reference())
}

/// One `AS_QD` entry: either a value or the refusal of the randomised branch.
pub type AsQualByDepthEntry = Result<f64, QualByDepthError>;

/// `AS_QualByDepth.finalizeRawData`: one quality-by-depth per alternate.
///
/// `None` is the reference's null: neither quality key present, or no genotypes, or no `AD`
/// anywhere.
#[allow(clippy::type_complexity)]
pub fn as_qual_by_depth(
    vc: &VariantContext,
    as_qual: Option<&str>,
    as_raw_qual_approx: Option<&str>,
    as_variant_depth: Option<&str>,
) -> Result<Option<Vec<AsQualByDepthEntry>>, AsSiteStatisticError> {
    if as_qual.is_none() && as_raw_qual_approx.is_none() {
        return Ok(None);
    }
    if vc.genotypes.is_empty() {
        return Ok(None);
    }
    let depths: Vec<i32> = match as_variant_depth {
        Some(text) => {
            let mut out = Vec::new();
            for piece in text.split(RAW_DELIM) {
                out.push(piece.trim().parse::<i32>().map_err(|_| {
                    AsSiteStatisticError::Malformed {
                        raw: piece.to_string(),
                    }
                })?);
            }
            out
        }
        None => match allele_depths(vc) {
            // "all no-calls and homRefs".
            None => return Ok(None),
            Some(depths) => depths,
        },
    };
    let quals = parse_qual_list(vc.alleles.len(), as_qual, as_raw_qual_approx)?;

    let reference_depth = depths[0] as f64;
    let mut out = Vec::with_capacity(quals.len());
    for (index, qual) in quals.iter().enumerate() {
        // The reference's depth is added to every alternate's denominator; see the module note.
        let denominator = depths[index + 1] as f64 + reference_depth;
        let value = *qual as f64 / denominator;
        if value >= MAX_QD_BEFORE_FIXING {
            out.push(Err(QualByDepthError::RandomisedAboveThreshold {
                raw: value,
            }));
        } else {
            out.push(Ok(value));
        }
    }
    Ok(Some(out))
}

/// `AnnotationUtils.encodeValueList(list, format)`: the values joined with commas.
pub fn encode_value_list(values: &[f64], places: usize) -> String {
    values
        .iter()
        .map(|value| format_decimals(*value, places))
        .collect::<Vec<_>>()
        .join(",")
}

/// `AS_RMSMappingQuality.getRMSDataFromLikelihoods`: a sum of squared mapping qualities per allele.
///
/// Absent rather than zero for an allele no informative read was assigned to, which is what makes
/// the difference between a written `0.00` and a missing value once the string is built.
pub fn as_rms_data(likelihoods: &AlleleLikelihoods<BamRecord>) -> Vec<(Allele, Option<f64>)> {
    let mut per_allele: Vec<(Allele, Option<f64>)> = (0..likelihoods.number_of_alleles())
        .filter_map(|index| likelihoods.get_allele(index).cloned())
        .map(|allele| (allele, None))
        .collect();
    for best in likelihoods.best_alleles_breaking_ties(None) {
        if !best.is_informative() {
            continue;
        }
        let Some(allele) = best.allele.as_ref() else {
            continue;
        };
        let Some(read) = likelihoods
            .sample_evidence(likelihoods.index_of_sample(&best.sample).unwrap_or(0))
            .and_then(|reads| reads.get(best.evidence_index))
        else {
            continue;
        };
        let mq = mapping_quality(read);
        if mq == 255 {
            continue;
        }
        if let Some(slot) = per_allele.iter_mut().find(|(a, _)| a == allele) {
            // `mq * mq` is an **int** multiplication in the reference, promoted to double only on
            // the addition, so a mapping quality above 46340 would overflow. None can: the field is
            // a byte.
            let square = (mq as i32 * mq as i32) as f64;
            slot.1 = Some(slot.1.unwrap_or(0.0) + square);
        }
    }
    per_allele
}

/// `AS_RMSMappingQuality.makeRawAnnotationString`: `%.2f` per allele, with a missing allele written
/// as `0.00` rather than left empty.
pub fn as_rms_raw_string(alleles: &[Allele], per_allele: &[(Allele, Option<f64>)]) -> String {
    alleles
        .iter()
        .map(|allele| {
            let value = per_allele
                .iter()
                .find(|(a, _)| a == allele)
                .and_then(|(_, value)| *value)
                .unwrap_or(0.0);
            format_decimals(value, 2)
        })
        .collect::<Vec<_>>()
        .join(&RAW_DELIM.to_string())
}

/// `AS_RMSMappingQuality.parseRawDataString`: positional over the alleles, an empty slot being null.
pub fn as_rms_parse_raw(
    alleles: &[Allele],
    raw: &str,
) -> Result<Vec<(Allele, Option<f64>)>, AsSiteStatisticError> {
    let mut out: Vec<(Allele, Option<f64>)> = alleles
        .iter()
        .map(|allele| (allele.clone(), None))
        .collect();
    // `String.split(regex)` without a limit, so trailing empty slots are dropped and the alleles
    // they would have filled keep their null.
    let mut tokens: Vec<&str> = raw.split(RAW_DELIM).collect();
    while tokens.last().is_some_and(|token| token.is_empty()) {
        tokens.pop();
    }
    for (index, token) in tokens.iter().enumerate() {
        if index >= out.len() {
            break;
        }
        if token.is_empty() {
            continue;
        }
        out[index].1 = Some(
            token
                .parse::<f64>()
                .map_err(|_| AsSiteStatisticError::Malformed {
                    raw: token.to_string(),
                })?,
        );
    }
    Ok(out)
}

/// `AS_RMSMappingQuality.getADcounts`: the alternates' `AD`s summed over every genotype.
///
/// Unlike `AS_QualByDepth.getAlleleDepths` this counts **every** genotype, called or not, and does
/// not require the alternate depth to exceed one. Two annotations, two definitions of the same
/// depth.
pub fn ad_counts(vc: &VariantContext) -> Option<Vec<(Allele, i32)>> {
    if vc.genotypes.is_empty() {
        // "VC does not have genotypes -- annotations were calculated in wrong order", then a null
        // that the caller dereferences.
        return None;
    }
    let mut counts: Vec<(Allele, i32)> = vc
        .alleles
        .iter()
        .map(|allele| (allele.clone(), 0))
        .collect();
    for genotype in &vc.genotypes {
        let Some(ad) = &genotype.ad else { continue };
        // "here -1 is to reconcile allele index with alt allele index": the reference's own slot is
        // never touched, so `AS_MQ` divides by a depth that is zero for the reference by
        // construction and never asks for it.
        for (slot, value) in counts.iter_mut().zip(ad.iter()).skip(1) {
            slot.1 += value;
        }
    }
    Some(counts)
}

/// `AS_RMSMappingQuality.makeFinalizedAnnotationString`: the root mean square per alternate.
///
/// An allele present with a null value is the missing value; an allele absent from the map is
/// **skipped entirely**, so the field can be shorter than the alternate count.
pub fn as_rms_finalized_string(
    vc: &VariantContext,
    per_allele: &[(Allele, Option<f64>)],
) -> Option<String> {
    let counts = ad_counts(vc)?;
    let mut out = String::new();
    for allele in vc.alternate_alleles() {
        let Some((_, value)) = per_allele.iter().find(|(a, _)| a == allele) else {
            // "ERROR: VC allele is not found in annotation alleles -- maybe there was trimming?"
            continue;
        };
        if !out.is_empty() {
            out.push(LIST_DELIMITER);
        }
        match value {
            None => out.push_str(MISSING_VALUE),
            Some(square_sum) => {
                let depth = counts
                    .iter()
                    .find(|(a, _)| a == allele)
                    .map(|(_, count)| *count)
                    .unwrap_or(0);
                out.push_str(&format_decimals(
                    jmath::math::sqrt(square_sum / depth as f64),
                    2,
                ));
            }
        }
    }
    Some(out)
}

/// `AS_InbreedingCoeff.calculateIC` for one alternate allele.
///
/// The biallelic branch derives the allele frequency from the **allele counts**, the multiallelic
/// one from `getCalledChrCount`. The comment on the first calls it a "shortcut to get a value closer
/// to the non-alleleSpecific value for biallelics", so the two branches are known not to agree and
/// the biallelic one is the one chosen to agree with `InbreedingCoeff`.
pub fn as_inbreeding_coefficient_for(
    vc: &VariantContext,
    alt: &Allele,
    counts: &HeterozygosityCounts,
) -> f64 {
    let het_count = counts.het_count(alt);
    let sample_count = counts.sample_count as f64;
    if vc.alleles.len() == 2 {
        let ref_ac = counts.allele_count(vc.reference());
        let alt_ac = counts.allele_count(alt);
        let ref_af = ref_ac / (alt_ac + ref_ac);
        let alt_af = 1.0 - ref_af;
        return 1.0 - (het_count / (2.0 * ref_af * alt_af * sample_count));
    }
    // `getCalledChrCount()`: every non-no-call allele across every genotype.
    let an = called_chromosome_count(vc) as f64;
    let alt_af = counts.allele_count(alt) / an;
    1.0 - (het_count / (2.0 * (1.0 - alt_af) * alt_af * sample_count))
}

/// `VariantContext.getCalledChrCount()`.
pub fn called_chromosome_count(vc: &VariantContext) -> usize {
    vc.genotypes
        .iter()
        .map(|genotype| genotype.alleles.iter().filter(|a| !a.is_no_call()).count())
        .sum()
}

/// `AS_InbreedingCoeff.annotate`: one coefficient per alternate, or nothing below ten samples.
pub fn as_inbreeding_coefficient(vc: &VariantContext) -> Option<String> {
    let counts = heterozygosity_counts(vc);
    if counts.sample_count < MIN_SAMPLES {
        return None;
    }
    let values: Vec<f64> = vc
        .alternate_alleles()
        .iter()
        .map(|alt| as_inbreeding_coefficient_for(vc, alt, &counts))
        .collect();
    Some(encode_value_list(&values, 4))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_qual_approx_form_drops_the_references_slot_and_reads_an_empty_one_as_zero() {
        assert_eq!(parse_qual_list(3, None, Some("0|30|")), Ok(vec![30, 0]));
        assert_eq!(
            parse_qual_list(3, None, Some("0|30")),
            Err(AsSiteStatisticError::QualApproxCountMismatch {
                found: 2,
                expected: 3
            })
        );
    }

    #[test]
    fn the_reference_depth_lands_in_every_alternates_denominator() {
        let mut vc = VariantContext::new(
            "chr1",
            100,
            vec![
                Allele::from_str("A", true).expect("an allele"),
                Allele::from_str("C", false).expect("an allele"),
                Allele::from_str("G", false).expect("an allele"),
            ],
        );
        vc.stop = 100;
        let mut genotype = htsjdk_vcf::variant::Genotype::new(
            "s1",
            vec![
                Allele::from_str("A", true).expect("an allele"),
                Allele::from_str("C", false).expect("an allele"),
            ],
        );
        genotype.ad = Some(vec![10, 4, 6]);
        vc.genotypes.push(genotype);
        let out = as_qual_by_depth(&vc, Some("70,140"), None, None)
            .expect("a parse")
            .expect("a value");
        // 70 / (4 + 10) = 5, and 140 / (6 + 10) = 8.75: the ten reference reads count twice.
        assert_eq!(out[0], Ok(5.0));
        assert_eq!(out[1], Ok(8.75));
    }
}
